version: '3.1'
services:
  backend:
    container_name: la-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${LEVIATAN_DB_PASSWORD}
      POSTGRES_USER: ${LEVIATAN_DB_USERNAME}
      POSTGRES_DB: ${LEVIATAN_DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true