version: '3.1'
services:
  backend:
    container_name: la-backend
    build: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD= ${LEVIATAN_DB_PASSWORD}
      - POSTGRES_USER=postgres