version: '3.1'
services:
  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: leviatan
    volumes:
      - /var/lib/postgresql/data

volumes:
  pgdata:
    external: true