///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.89Release
// Tag = production/akw/21.89.00-0-g487f2ed0
///////////////////////////////////////////////////////////////////////////////////


package com.leviatan.fit.util;

public final class SemicirclesConverter {
    static final double PI_RADIANS = 0x80000000L;

    static final double CONVERSION_FACTOR = 180.0 / PI_RADIANS;

    public static double semicirclesToDegrees(int semicircles) {
        double degrees = 0.0;

        degrees = semicircles * CONVERSION_FACTOR;

        return degrees;
    }

    public static int degreesToSemicircles(double degrees) {
        int semicircles = 0;

        semicircles = (int) (degrees / CONVERSION_FACTOR);

        return semicircles;
    }
}
